---
title: >
  The `annoFuseData` User's Guide
author:
- name: Federico Marini
  affiliation: 
  - &id1 Institute of Medical Biostatistics, Epidemiology and Informatics (IMBEI), Mainz
  - Center for Thrombosis and Hemostasis (CTH), Mainz
  email: marinif@uni-mainz.de
- name: Krutika Gaonkar
  affiliation: 
  - &id2 Center for Data-Driven Discovery in Biomedicine, Children’s Hospital of Philadelphia, USA
  email: gaonkark@chop.email.edu
date: "`r BiocStyle::doc_date()`"
package: "`r BiocStyle::pkg_ver('annoFuseData')`"
output: 
  BiocStyle::html_document:
    toc_float: true
    number_sections: true
vignette: >
  %\VignetteIndexEntry{The annoFuseData User's Guide}
  %\VignetteEncoding{UTF-8}  
  %\VignettePackage{annoFuseData}
  %\VignetteKeywords{Software, Transcription, Visualization, GeneExpression, Annotation,
    GeneFusionDetection, GUI, ReportWriting}
  %\VignetteEngine{knitr::rmarkdown}
---  

<style type="text/css">
.smaller {
  font-size: 10px
}
</style>

**Compiled date**: `r Sys.Date()`

**Last edited**: 2020-11-11

**License**: `r packageDescription("annoFuseData")[["License"]]`

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment  = "#>",
  error    = FALSE,
  warning  = FALSE,
  eval     = TRUE,
  message  = FALSE,
  fig.width = 10
)
options(width = 100)
```

---

# Introduction {#introduction}

```{r}
library("annoFuseData")
```

```{r}

```


# Session info {- .smaller}

```{r}
sessionInfo()
```


